### ISSUE TITLE
Make tests green again

### ISSUE THREAD

**Issue by sanpii** [Behatch/contexts#242]
We have two problems with CI:

* [x] atoum doesn’t have maximum php value contrains, with php >= 7.1 the new reserved keyword `void` throws an error: https://travis-ci.org/Behatch/contexts/jobs/348405221#L657
* [ ] behat tests fail due to new webdriver achitecture: https://travis-ci.org/Behatch/contexts/jobs/348405218#L658

All works fine on my computer and I am a little tired to push & wait travis fail.

**Comment by ilovemistakes** [comment]
Behat fails due to Behat/MinkExtension#309 , which is fixed in the recently released 2.3.1 version (Behat/MinkExtension#311). I see two options:

1. Update composer.json to require "^2.3.1" of "behat/mink-extension" instead of "^2.0". A long jump.
2. Explicitly specify the "marionette" parameter in "behat.yml.dist" as a workaround:
```
            selenium2:
                capabilities:
                    marionette: null
```
I used it to run tests locally. More preferable, i think.
What do you think, @sanpii ?

**Comment by sanpii** [comment]
@ilovemistakes No, it’s still failed [with](https://travis-ci.org/Behatch/contexts) or [without](https://travis-ci.org/Behatch/contexts/builds/350329933) chrome driver.

**Comment by OskarStark** [comment]
@sanpii could you create a PR where we can comment and check the travis build?

**Comment by sanpii** [comment]
@OskarStark Done. I also relaunched the travis build, but I think it is blocked by selinium (it launch the browser but it can’t control its).

**Comment by ilovemistakes** [comment]
I've reproduced this in the docker container. Chrome runs in a sandbox mode by default, which is utilizing linux kernel's user_namespaces and other features for resource isolation. It seems that sandbox is not available in a docker container because containers are run in unprivileged mode by default. So, for travis builds we need to start chrome with "--no-sandbox" option:
```
selenium2:
  capabilities:
    chrome:
      switches: ["--no-sandbox"]
```

**Comment by ilovemistakes** [comment]
Btw, behat still fails on `tests/features/rest.feature:91` with PHP 5.5.38 because of [this PHP bug](https://bugs.php.net/bug.php?id=66606). php/php-src#886 has not been merged to the 5.5 branch. `$_SERVER['CONTENT_TYPE']` doesn't get populated.

**Comment by OskarStark** [comment]
Good job @ilovemistakes 👍

**Comment by sanpii** [comment]
@ilovemistakes thank you very much, that works :tada:

https://travis-ci.org/Behatch/contexts/builds/351320817
